[project]
name = "bitbasel-marketplace"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/Users/alacret/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.traits]
path = "contracts/traits.clar"
depends_on = []

[contracts.test-token]
path = "contracts/test-token.clar"
depends_on = ["traits"]

[contracts.bitbasel-marketplace]
path = "contracts/bitbasel-marketplace.clar"
depends_on = ["traits"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
